// THIS CODE IS PROTECTED UNDER THE COPYRIGHT, DESIGNS AND PATENTS ACT 1988.
// NOT AUTHORIZED FOR REDISTRIBUTION OR MODIFICATION UNDER ANY PARTIES OTHER THAN THE ORIGINAL CREATORS.
// UNAUTHORIZED MODIFICATION CAN RESULT IN LEGAL ACTION.
